### ISSUE TITLE
Issue about a paper you published on  International Conference on Web Services 2017

### ISSUE THREAD

**Issue by xiaotret** [prisams/test#1]
Hello,Priyanka. I'm a postgraduate from Wuhan university,China.
I am very interested in the article  'Recommending Services for New Mashups Through Service Factors and Top-K Neighbors' that you published on  the ICWS2017. I want to use your method as a baseline algorithm  and quote your research in my paper. But I don't  find the code for this project on your github homepage. Could you release your code on your homepage or email to me at 1572524664@qq.com ,please? I will appreciate it very much if you do that.

**Comment by prisams** [comment]
Thank you for reaching out to me. I apologize that it is not on github yet. I will post it by this weekend and share with you.

**Comment by xiaotret** [comment]
I'm sorry but you seem to have forgotten to send the code of 'Recommending Services for New Mashups Through Service Factors and Top-K Neighbors' to me. You can email to me at 1572524664@qq.com when you have free time.
       Thank you very mach.
